### ISSUE TITLE
magicffi doesn't compile on windows

### ISSUE THREAD

**Issue by diasbruno** [lisp-maintainers/file-finder#1]
This package would be really great for windows users (currently I need it for work).

**Comment by diasbruno** [comment]
I'll try to have a look on this later.

**Comment by vindarel** [comment]
Ah crap. I'm more than OK to remove this functionality though. And then:

- add something about MIME types with https://github.com/Shinmera/trivial-mimes
- re-add this magicffi feature in a separate system.

I'm primarily interested in the search features and having a minimal and easy to use library, and then more features.

**Comment by diasbruno** [comment]
Great. I'll see what I can do.

**Comment by diasbruno** [comment]
I've tried to find something that could be used on windows, but the closest I've found was [julian-r/file-windows](https://github.com/julian-r/file-windows).

**Comment by diasbruno** [comment]
I'll give it a try later.

**Comment by vindarel** [comment]
but is it actually useful to get information with trivial-mimes? We only get a mapping file extension -> mime type, it doesn't inspect the file content like libmagic/magicffi.

**Comment by diasbruno** [comment]
Would you like to drop mimes and encoding for now?

**Comment by vindarel** [comment]
yeah, and we take the time to add them if we ever need them.

**Comment by vindarel** [comment]
we removed magicffi.
